twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:     
        uuid: '@App\Service\Globals\AppConfigs'
        ga_tracking: '2.0'
        
when@test:
    twig:
        strict_variables: true
